# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:


    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Pacotes do Maven
      run: mvn -B package --file pom.xml

    - name: Compilar projeto
      run: mvn compile
      
    - name: Executando o projeto
      run: java -cp target/classes org.example.Main
    
    #- name: Git Version
    #  id: generate_number
    #  uses: codacy/git-version@2.4.0
    #  with:
    #    # The name of the release branch
    #    release-branch: master
    #    # The prefix to use in the version
    #    prefix: PROD-
    
    #- name: Get next version
    #  id: get_next_version
    #  uses: thenativeweb/get-next-version@main
    #- name: Show the next version
    #  run: |
    #    echo ${{ steps.get_next_version.outputs.version }}
    #    echo ${{ steps.get_next_version.outputs.hasNextVersion }}
    
    - uses: PssbleTrngle/VersionManagment@v2
      id: version
      with:
        token: ${{secrets.GITHUB_TOKEN}}
        fallback: v0.1.0
        prefix: v 
   
    #- uses: actions/checkout@v2
    #- id: version
    #  uses: docker://lpenz/ghaction-version-gen:0.7 
    
    #- name: Create Release
    #  uses: actions/create-release@v1
    #  env:
    #      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
    #  with:
    #      tag_name: ${{ github.run_number }}
    #      release_name: ${{ github.run_number }}

    - uses: mr-smithers-excellent/docker-build-push@v6
      name: Build & push Docker image
      with:
          image: nisflei/aula_maven_e
          #steps.generate_number.outputs.VERSION
          tags: 1.0, ${{ github.run_number }}, ${{ steps.version.outputs.next }}
          registry: docker.io
          dockerfile: dockerfile
          username: ${{ secrets.DOCKER_USUARIO }}
          password: ${{ secrets.DOCKER_SENHA }}         
